### ISSUE TITLE
encoding error with warc2htmlwarc

### ISSUE THREAD

**Issue by wwaites** [bitextor/bitextor#140]
This is operating on /data/internet_archive/SURV-20141218225408-crawl426/SURV-20141218230710-00052.warc.gz

    Traceback (most recent call last):
      File "/home/shared/wwaites/miniconda3/envs/bitextor/lib/python3.7/site-packages/warcio/statusandheaders.py", line 175, in to_ascii_bytes
        string = string.encode('ascii')
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 243-246: ordinal not in range(128)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/shared/wwaites/bitextor/bitextor-warc2htmlwarc.py", line 242, in <module>
        fo.write_record(newrecord)
      File "/home/shared/wwaites/miniconda3/envs/bitextor/lib/python3.7/site-packages/warcio/warcwriter.py", line 137, in write_record
        self._write_warc_record(self.out, record)
      File "/home/shared/wwaites/miniconda3/envs/bitextor/lib/python3.7/site-packages/warcio/warcwriter.py", line 46, in _write_warc_record
        record.http_headers.compute_headers_buffer(self.header_filter)
      File "/home/shared/wwaites/miniconda3/envs/bitextor/lib/python3.7/site-packages/warcio/statusandheaders.py", line 118, in compute_headers_buffer
        self.headers_buff = self.to_ascii_bytes(header_filter)
      File "/home/shared/wwaites/miniconda3/envs/bitextor/lib/python3.7/site-packages/warcio/statusandheaders.py", line 179, in to_ascii_bytes
        string = string.encode('ascii')
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 249-252: ordinal not in range(128)

**Comment by lpla** [comment]
We are going to reproduce it. Please, check that you are using latest master code, as we merged all development branches into master, fixing some bugs on its way.

**Comment by wwaites** [comment]
The offending header is:

    Powered-By-FiRadio.com: <a href*=UTF-8''//www.firadio.com>飞儿传媒</a><script src*=UTF-8''//cdn.firadio.com/firadio/tongji.js></script>

**Comment by wwaites** [comment]
That header looks totally not kosher but... Postel's Law...

**Comment by lpla** [comment]
We know that `warcio` has some problems with HTTP response headers with non ASCII data, that's why we tried to manage it in warc2htmlwarc script:

https://github.com/bitextor/bitextor/blob/9007c5e15f045b3e6fd520330022ad97b7a7ac2a/bitextor-warc2htmlwarc.py#L201-L206
We thought that we covered all cases, but give us some time to reproduce it.

**Comment by wwaites** [comment]
it looks like updating to the master branch works...

**Comment by wwaites** [comment]
you already fixed it. thanks!
