### ISSUE TITLE
bitextor-tokenizer error without --morph-analyser (which is not required)

### ISSUE THREAD

**Issue by kpu** [bitextor/bitextor#162]
According to the options configuration, a morphological analyzer is optional:
https://github.com/bitextor/bitextor/blob/88f1744115f6afea7209b6733a64a2415f8370e8/bitextor-tokenize.py#L56

However, when run without one, the script generates a gigantic error message:
```
Traceback (most recent call last):
  File "/raid0/heafield/bitextor/utils/common.py", line 34, in open_xz_or_gzip_or_plain
    yield f
  File "/fs/snotra0/heafield/bitextor/bitextor-tokenize.py", line 65, in <module>
    sentences, tokenized = extract_encoded_text(encoded_text, os.path.expanduser(options.splitter), os.path.expanduser(options.tokenizer), os.path.expanduser(options.lemmatizer))
  File "/fs/snotra0/heafield/bitextor-venv/lib/python3.5/posixpath.py", line 228, in expanduser
    if not path.startswith(tilde):
AttributeError: 'NoneType' object has no attribute 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid0/heafield/bitextor/utils/common.py", line 34, in open_xz_or_gzip_or_plain
    yield f
  File "/fs/snotra0/heafield/bitextor/bitextor-tokenize.py", line 68, in <module>
    tok_writer.write(tokenized + b"\n")
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/raid0/heafield/bitextor/utils/common.py", line 37, in open_xz_or_gzip_or_plain
    raise Exception("Error occurred while loading a file!")
Exception: Error occurred while loading a file!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid0/heafield/bitextor/utils/common.py", line 34, in open_xz_or_gzip_or_plain
    yield f
  File "/fs/snotra0/heafield/bitextor/bitextor-tokenize.py", line 68, in <module>
    tok_writer.write(tokenized + b"\n")
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/raid0/heafield/bitextor/utils/common.py", line 37, in open_xz_or_gzip_or_plain
    raise Exception("Error occurred while loading a file!")
Exception: Error occurred while loading a file!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fs/snotra0/heafield/bitextor/bitextor-tokenize.py", line 68, in <module>
    tok_writer.write(tokenized + b"\n")
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/raid0/heafield/bitextor/utils/common.py", line 37, in open_xz_or_gzip_or_plain
    raise Exception("Error occurred while loading a file!")
Exception: Error occurred while loading a file!
```

**Comment by zuny26** [comment]
Thank you for reporting, should be fixed now
