### ISSUE TITLE
error in bitextor-identifyMIME.py

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#35]
Input file attached

# bitextor-identifyMIME.py < 18thcenturyblog.tt
...
Traceback (most recent call last):
  File "/home/hieu/permanent/software/bitextor/bitextor-identifyMIME.py", line 33, in <module>
    magicoutput=m.buffer(base64.b64decode(content)).split(" ")
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by hieuhoang** [comment]
attaching now

[18thcenturyblog.zip](https://github.com/bitextor/bitextor/files/2561404/18thcenturyblog.zip)

**Comment by hieuhoang** [comment]
I've committed this fix https://github.com/bitextor/bitextor/commit/907434ad92a88391e2f229bd27102c413bee856b
according to advise from 
   https://gist.github.com/perrygeo/ee7c65bb1541ff6ac770
A bit hacky, there may be better ways of doing this
