### ISSUE TITLE
warc2preprocess error

### ISSUE THREAD

**Issue by hieuhoang** [bitextor/bitextor#88]
Running this command:
   xzcat concat.warc.xz -f |  nice ionice -c 3 bitextor-warc2preprocess.py  --output-dir transient/miyakyo-u --lang1 da --lang2 en
produces this error:

Traceback (most recent call last):
  File "/home/s0565741/workspace/github/paracrawl/bitextor.malign/bitextor-warc2preprocess.py", line 114, in <module>
    lang = guess_lang_from_data2(tree)
  File "/home/s0565741/workspace/github/paracrawl/bitextor.malign/bitextor-warc2preprocess.py", line 27, in guess_lang_from_data2
    data, isPlainText=False)
pycld2.error: input contains invalid UTF-8 around byte 100 (of 2130)

Affecting quite a lot of warcs recently. Warc files don't seem to be corrupted. Warc file here:
   http://statmt.org/hieu/paracrawl/concat.warc.xz

**Comment by lpla** [comment]
Working on it.

**Comment by hieuhoang** [comment]
cheers my dears. Gonna run it now
